### ISSUE TITLE
Version 2 checklist

### ISSUE THREAD

**Issue by joelambert** [Rareloop/primer-core#1]
- [x] Update docs on main repo
- [x] Update docs on twig template engine
  - [x] `{% include %}` docs
  - [x]  Add info about using `{% extends %}` and templating/view wrapping
- [x] Update base patterns in the twig repo
- [x] Submit template engines to packagist
- [x] Lock down composer.json on main repo
- [x] Make sure change log makes sense
- [x] Delete `composer.lock` from the main repo
- [x] add updated screenshot back into readme
